// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalUkLBElrcHBqLqTFJ_FEEBNAdxfjW54',
    appId: '1:366278746826:android:72b44ba6b747aaad1eca33',
    messagingSenderId: '366278746826',
    projectId: 'minna-ai-n5',
    storageBucket: 'minna-ai-n5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA667kpJuuT_9gOSe0uECLykr3LTSWmI88',
    appId: '1:366278746826:ios:ad47ad86db399c5c1eca33',
    messagingSenderId: '366278746826',
    projectId: 'minna-ai-n5',
    storageBucket: 'minna-ai-n5.firebasestorage.app',
    iosClientId: '366278746826-jdohs95deracslsba7d6a8t3j9hk30od.apps.googleusercontent.com',
    iosBundleId: 'com.example.minnaAiN5',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VXDZT_oH-H8m-KX9DJBSffpg2BxcY40',
    appId: '1:366278746826:web:e870e484aae94f261eca33',
    messagingSenderId: '366278746826',
    projectId: 'minna-ai-n5',
    authDomain: 'minna-ai-n5.firebaseapp.com',
    storageBucket: 'minna-ai-n5.firebasestorage.app',
    measurementId: 'G-SW2KD24486',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA667kpJuuT_9gOSe0uECLykr3LTSWmI88',
    appId: '1:366278746826:ios:ad47ad86db399c5c1eca33',
    messagingSenderId: '366278746826',
    projectId: 'minna-ai-n5',
    storageBucket: 'minna-ai-n5.firebasestorage.app',
    iosClientId: '366278746826-jdohs95deracslsba7d6a8t3j9hk30od.apps.googleusercontent.com',
    iosBundleId: 'com.example.minnaAiN5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3VXDZT_oH-H8m-KX9DJBSffpg2BxcY40',
    appId: '1:366278746826:web:05af425b2bd755031eca33',
    messagingSenderId: '366278746826',
    projectId: 'minna-ai-n5',
    authDomain: 'minna-ai-n5.firebaseapp.com',
    storageBucket: 'minna-ai-n5.firebasestorage.app',
    measurementId: 'G-5SEE4SG5Q3',
  );

}